import Navigation from '../components/navigation';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}

//-------------✅ Layout
// --> 예를 들어 NavBar는 여러 컴포넌트에서 사용한다. 그럼 각 컴포넌트마다 일일이 코드를 복붙해야 하나?
// 이 때 필요한 것이 Layout!
//Next.js는 layout컴포넌트에 있는 export된 컴포넌트들을 렌더링 한다.

//<Layout>
//	<여기에 페이지 컴포넌트들이 들어가고 렌더링 되는 것/>
//</Layout>

// --> Layout이 여러개 필요하다면? 사용하는 페이지다 다른 레이아웃이 필요할 수 있다. 레이아웃 중첩 가능!
//해당 폴더 안에 page.tsx와 함께 layout.tsx파일을 만들면 된다!
//상위로 올라가면서 레이아웃 파일이 있다면, 알아서 해당 레이아웃을 사용해서 하위 항목을 렌더링해준다.
// --> 최상단 레이아웃이 기본이고 나머지 폴더에 레이아웃이 있다면 알아서 적용 시켜주는 것!

//(오 여기 레이아웃이랑 페이지 보여줘야겠군. 상위 폴더로 가자. 여긴 페이지만 있네 ㅇㅋ, 상위 폴더로 가자. 여기도 레이아웃, 페이지 있네. ㅇㅋ 그럼 이렇게 해서 적용시키면 되겠군 ~)
